### ISSUE TITLE
Test Requests with VCR (Real model only)

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-xenserver#27]
* [x] Create a method on [fog-core](https://github.com/fog/fog-core) to get all attributes of an instance as a hash, regardless if it was passed to `merge_attributes` or not. (see fog/fog-core#59)
* [x] Create association methods and as attribute type on [fog-core](https://github.com/fog/fog-core) to create setters that can receive an Model instead of only the reference. (see fog/fog-core#60 fog/fog-core#62 fog/fog-core#65 fog/fog-core#66)
* [x] Create a method on [fog-core](https://github.com/fog/fog-core) to get all attributes of an instance including the associations. (see fog/fog-core#68 fog/fog-core#69 fog/fog-core#70)
* [x] New `fog-core` release (see fog/fog-core#72)
* [x] Add alias option to associations in [fog-core](https://github.com/fog/fog-core) (see fog/fog-core#73)
* [x] Refactor models to use the new association methods
* [x] Add support to remap the attribute names on hash generation `all_attributes` (see fog/fog-core#74)
* [x] Refactor request methods (Remove bad code)
* [x] Test with VCR
* [x] Deprecate old api in [fog](https://github.com/fog/fog)

**Comment by plribeiro3000** [comment]
In the release [1.27.0](https://github.com/fog/fog/tree/v1.27.0) all the apis that will change when moving to this repo were deprecated so this closes this issue.

Some release ahead we will drop the old api from `Fog` and add this gem as dependency marking this repo as the official repository to support `Xenserver` in `Fog`.
